#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  btn1,           sensorTouch)
#pragma config(Sensor, dgtl2,  btn2,           sensorTouch)
#pragma config(Sensor, dgtl3,  btn3,           sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_mm)
#pragma config(Motor,  port2,           liftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           light1,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port4,           light2,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port5,           light3,        tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

}
